// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAupnsWua23yD1DN5HF6CdtFvgP9u1hcE',
    appId: '1:943066306261:android:b818fb7736091b95e5f45c',
    messagingSenderId: '943066306261',
    projectId: 'practice-eae36',
    storageBucket: 'practice-eae36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_hrPA2DpESgHjhzaqepOTFoz_HiUhtQ',
    appId: '1:943066306261:ios:ee523782ee48b367e5f45c',
    messagingSenderId: '943066306261',
    projectId: 'practice-eae36',
    storageBucket: 'practice-eae36.appspot.com',
    androidClientId: '943066306261-st1uq2rfqc2qr3fj5r6f6lbg6te5iigm.apps.googleusercontent.com',
    iosClientId: '943066306261-n79n6gumvbfrjulpt5sp04n9ouoi08cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerDemo',
  );
}
